language: go

os:
  - linux

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

sudo: required
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - sudo apt-get update -qq
  - sudo apt-get install -y fonts-roboto

script:
  - go test -v -tags ci ./...
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: always
